// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Ignore = sequelize.define('ignore', {
    createdAt: {
      type: DataTypes.DATE,
    },
    updatedAt: {
      type: DataTypes.DATE,
    },
    userId: {
      type: DataTypes.INTEGER,
      field: 'UserId',
      primaryKey: true,
      allowNull: false,
    },
    ignoringId: {
      type: DataTypes.INTEGER,
      field: 'IgnoringId',
      primaryKey: true,
      allowNull: false,
    },
  }, {
    tableName: 'ignore',
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  Ignore.associate = (models) => {
    Ignore.belongsTo(models.users, {
      foreignKey: {
        name: 'userIdKey',
        field: 'UserId',
      },
      as: 'user',
    });
    Ignore.belongsTo(models.users, {
      foreignKey: {
        name: 'ignoringIdKey',
        field: 'IgnoringId',
      },
      as: 'ignoring',
    });
  };

  return Ignore;
};
